# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_advertiseraaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertiseraaddress',
            options={'verbose_name': 'Advertisera Address'},
        ),
    ]
