# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_auto_20180119_1239'),
        ('ad_payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_number', models.CharField(max_length=234)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_advertisement', to='advertisements.Advertisement')),
            ],
        ),
    ]
