# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_payment', '0002_advertisementpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementpayment',
            options={'verbose_name': 'AdvertisementPayment', 'verbose_name_plural': 'AdvertisementPayment'},
        ),
        migrations.RemoveField(
            model_name='advertisementpayment',
            name='charge_number',
        ),
        migrations.AddField(
            model_name='advertisementpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=234),
        ),
        migrations.AlterField(
            model_name='advertisementpayment',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_advertisement', to='advertisements.Advertisement'),
        ),
    ]
