# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_payment', '0003_auto_20180201_0931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.AlterModelOptions(
            name='advertisementpayment',
            options={'verbose_name': 'Advertisement Payment', 'verbose_name_plural': 'Advertisement Payment'},
        ),
    ]
